import java.util.Scanner;

class Scanner{
    public static void main(String[] args){
        Scanner scan = new Scanner(System.in);

        // putting scan.nextLine() after nextInt() skips the input for string because of the Scanner.nextInt
        // method does not read the newline character in the input generated by hitting "Enter," and so the 
        // call to Scanner.nextLine retorts after reading that newline.
        
        int a = scan.nextInt();
        double d = scan.nextDouble();
        scan.nextLine(); // Consume newline left-over
        String s = scan.nextLine();

        System.out.println(a);
        System.out.println(d);
        System.out.println(s);
    }
}